"""
Concatenate base.css with variant partials to produce self-contained CSS files.

Each variant (root, data, insights) = base.css + _<variant>.css.
Generated files are consumed by notebooks via marimo's css_file parameter.

Usage:
    uv run scripts/build_css.py
"""

import sys
from pathlib import Path

STYLES_DIR = Path(__file__).parent.parent / "notebooks" / "styles"
BASE = STYLES_DIR / "base.css"
VARIANTS = ["root", "data", "insights"]


def build():
    if not BASE.exists():
        print(f"ERROR: {BASE} not found", file=sys.stderr)
        sys.exit(1)

    base_css = BASE.read_text()
    built = []

    for name in VARIANTS:
        partial = STYLES_DIR / f"_{name}.css"
        output = STYLES_DIR / f"{name}.css"

        if not partial.exists():
            print(f"ERROR: {partial} not found", file=sys.stderr)
            sys.exit(1)

        combined = (
            f"/* Generated by build_css.py — do not edit directly. */\n"
            f"/* Source: base.css + _{name}.css */\n\n"
            f"{base_css}\n\n"
            f"/* === {name.title()} variant overrides === */\n\n"
            f"{partial.read_text()}"
        )
        output.write_text(combined)
        built.append(name)

    print(f"Built {len(built)} CSS variant(s): {', '.join(built)}")


if __name__ == "__main__":
    build()
